media:
  input: images
  output: images

content:
  - name: settings
    label: "Edit Sales Page"
    type: file
    path: "content.json"
    fields:
      # Grouping makes it feel like an element selector
      - label: "--- SECTION 1: TOP BANNER ---"
        type: object
        fields:
          - { name: "hero_heading", label: "Main Heading Text", type: "string" }
          - { name: "image", label: "Hero Background Image", type: "image" }

      - label: "--- SECTION 2: PRODUCT DETAILS ---"
        type: object
        fields:
          - { name: "description", label: "Long Description", type: "text" }
          - { name: "video", label: "YouTube Video Link", type: "string" }

      - label: "--- SECTION 3: PRICING & BUTTON ---"
        type: object
        fields:
          - { name: "cta_url", label: "Formspree Link", type: "string" }
